### PR TITLE
Make packages linkable

### LINKED ISSUE #10: Link to packages
I just saw that the top* package is one I've never used.
It should be easy to remove offending packages.
A link could work, although there could be a more prominent (and direct) button to uninstall it as well
I was about to say maybe just have uninstall buttons for packages in the red, but that would be a bad idea.

*for loading. For package activation, status-bar is coming in at a whopping 2308ms

### PR DESCRIPTION
**Pull request by jerone**
Fixes #10

@kevinsawicki I saw you were assigned, but no progress so far.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Yeah, I'm not sure opening it in a browser is the best option here.

A link to the settings view for that package would seem better since you can disable it from there, see about any options or readme details about performance, and open up the repo as well.

**Comment by jerone** [comment]
Yeah I prefer to open the settings for that package too, but that's blocked by https://github.com/atom/settings-view/issues/436

**Comment by jerone** [comment]
I've updated the code to open the package settings page instead of the homepage.

/cc @kevinsawicki

**Comment by thedaniel** [comment]
shout out to `element.dataset` !

**Comment by jerone** [comment]
It's there for data :smiley: 

Yeeh for merging :tada:

**Pull request merged**
